// examples/mini-app-claim-react/src/App.tsx
import { translate } from '@nimiq-faucet/mini-app-claim-shared';
import { useMiniAppFaucet } from './hooks/useMiniAppFaucet';
import { FcaptchaWidgetView } from './components/FcaptchaWidget';

const FAUCET_URL = import.meta.env.VITE_FAUCET_URL ?? 'http://localhost:8080';
const EXPLORER_BASE = import.meta.env.VITE_EXPLORER_URL ?? 'https://nimiq-testnet.observer/#tx/';

export function App() {
  const { state, captchaPrompt, claim, reset, canClaim } = useMiniAppFaucet(FAUCET_URL);
  const t = translate;

  const buttonLabel =
    state.phase === 'awaiting-address' ||
    state.phase === 'awaiting-captcha' ||
    state.phase === 'submitting' ||
    state.phase === 'broadcast'
      ? t('claiming')
      : t('claim');

  const showButtonSpinner =
    state.phase !== 'ready' &&
    state.phase !== 'rejected' &&
    state.phase !== 'error' &&
    state.phase !== 'confirmed' &&
    state.phase !== 'connecting' &&
    state.phase !== 'outside-nimiq-pay';

  const explorerUrl = state.txId ? `${EXPLORER_BASE}${state.txId}` : null;

  return (
    <>
      <h1 className="title">{t('title')}</h1>
      <p className="subtitle">{t('subtitle')}</p>

      {state.phase === 'connecting' && (
        <div className="card">
          <span>
            <span className="spinner" />
            {t('connecting')}
          </span>
        </div>
      )}

      {state.phase === 'outside-nimiq-pay' && (
        <div className="card">
          <strong>{t('outsidePay')}</strong>
          <p className="subtitle">{t('outsidePayHint')}</p>
          {state.outsideReason && (
            <p className="subtitle">
              <small>{state.outsideReason}</small>
            </p>
          )}
        </div>
      )}

      {state.phase !== 'connecting' && state.phase !== 'outside-nimiq-pay' && (
        <>
          {state.address && (
            <div className="card">
              <span className="label">{t('addressFromWallet')}</span>
              <span className="address">{state.address}</span>
            </div>
          )}

          {captchaPrompt && (
            <FcaptchaWidgetView
              serverUrl={captchaPrompt.serverUrl}
              siteKey={captchaPrompt.siteKey}
              onSolved={captchaPrompt.resolve}
              onFailed={captchaPrompt.reject}
            />
          )}

          {state.phase === 'awaiting-captcha' && <p className="subtitle">{t('awaitingCaptcha')}</p>}

          <button className="btn" disabled={!canClaim} onClick={claim}>
            {showButtonSpinner && <span className="spinner" />}
            {buttonLabel}
          </button>

          {state.phase === 'broadcast' && (
            <div className="banner warn">
              <span className="spinner" />
              {t('broadcast')}
            </div>
          )}

          {state.phase === 'confirmed' && (
            <div className="banner good">
              <strong>{t('confirmed')}</strong>
              {state.txId && (
                <p className="tx">
                  {t('txLabel')}: {state.txId}
                </p>
              )}
              {explorerUrl && (
                <a href={explorerUrl} target="_blank" rel="noopener" className="link">
                  {t('explorerLink')} →
                </a>
              )}
            </div>
          )}

          {(state.phase === 'rejected' || state.phase === 'challenged') && (
            <div className="banner bad">
              <strong>{state.phase === 'challenged' ? t('challenged') : t('rejected')}</strong>
              {state.errorMessage && <p className="tx">{state.errorMessage}</p>}
              <button className="btn" onClick={reset}>
                {t('retry')}
              </button>
            </div>
          )}

          {state.phase === 'error' && (
            <div className="banner bad">
              <strong>{t('error')}</strong>
              {state.errorMessage && <p className="tx">{state.errorMessage}</p>}
              <button className="btn" onClick={reset}>
                {t('retry')}
              </button>
            </div>
          )}
        </>
      )}
    </>
  );
}

// examples/mini-app-claim-vue/src/App.vue
<script setup lang="ts">
import { computed } from 'vue';
import { translate } from '@nimiq-faucet/mini-app-claim-shared';
import { useMiniAppFaucet } from './composables/useMiniAppFaucet';
import FcaptchaWidget from './components/FcaptchaWidget.vue';

const faucetUrl = import.meta.env.VITE_FAUCET_URL ?? 'http://localhost:8080';
const explorerBase = import.meta.env.VITE_EXPLORER_URL ?? 'https://nimiq-testnet.observer/#tx/';

const { state, captchaPrompt, claim, reset, canClaim } = useMiniAppFaucet(faucetUrl);

const t = (key: Parameters<typeof translate>[0]) => translate(key);

const buttonLabel = computed(() => {
  switch (state.phase) {
    case 'awaiting-address':
    case 'awaiting-captcha':
    case 'submitting':
    case 'broadcast':
      return t('claiming');
    default:
      return t('claim');
  }
});

const explorerUrl = computed(() => (state.txId ? `${explorerBase}${state.txId}` : null));
</script>

<template>
  <h1 class="title">{{ t('title') }}</h1>
  <p class="subtitle">{{ t('subtitle') }}</p>

  <div v-if="state.phase === 'connecting'" class="card">
    <span><span class="spinner" />{{ t('connecting') }}</span>
  </div>

  <div v-else-if="state.phase === 'outside-nimiq-pay'" class="card">
    <strong>{{ t('outsidePay') }}</strong>
    <p class="subtitle">{{ t('outsidePayHint') }}</p>
    <p v-if="state.outsideReason" class="subtitle"><small>{{ state.outsideReason }}</small></p>
  </div>

  <template v-else>
    <div v-if="state.address" class="card">
      <span class="label">{{ t('addressFromWallet') }}</span>
      <span class="address">{{ state.address }}</span>
    </div>

    <FcaptchaWidget
      v-if="captchaPrompt"
      :server-url="captchaPrompt.serverUrl"
      :site-key="captchaPrompt.siteKey"
      @solved="captchaPrompt.resolve($event)"
      @failed="captchaPrompt.reject($event)"
    />

    <p v-if="state.phase === 'awaiting-captcha'" class="subtitle">
      {{ t('awaitingCaptcha') }}
    </p>

    <button
      class="btn"
      :disabled="!canClaim"
      @click="claim"
    >
      <span v-if="state.phase !== 'ready' && state.phase !== 'rejected' && state.phase !== 'error' && state.phase !== 'confirmed'" class="spinner" />
      {{ buttonLabel }}
    </button>

    <div v-if="state.phase === 'broadcast'" class="banner warn">
      <span class="spinner" />{{ t('broadcast') }}
    </div>

    <div v-else-if="state.phase === 'confirmed'" class="banner good">
      <strong>{{ t('confirmed') }}</strong>
      <p v-if="state.txId" class="tx">{{ t('txLabel') }}: {{ state.txId }}</p>
      <a v-if="explorerUrl" :href="explorerUrl" target="_blank" rel="noopener" class="link">
        {{ t('explorerLink') }} →
      </a>
    </div>

    <div v-else-if="state.phase === 'rejected' || state.phase === 'challenged'" class="banner bad">
      <strong>{{ state.phase === 'challenged' ? t('challenged') : t('rejected') }}</strong>
      <p v-if="state.errorMessage" class="tx">{{ state.errorMessage }}</p>
      <button class="btn" @click="reset">{{ t('retry') }}</button>
    </div>

    <div v-else-if="state.phase === 'error'" class="banner bad">
      <strong>{{ t('error') }}</strong>
      <p v-if="state.errorMessage" class="tx">{{ state.errorMessage }}</p>
      <button class="btn" @click="reset">{{ t('retry') }}</button>
    </div>
  </template>
</template>
